[package]
name = "Spam"
version = "1.0.0"
edition = "2024.beta"
license = "Apache-2.0"

published-at = "0x0"

[dependencies]
Sui = { local = "../../../sui/crates/sui-framework/packages/sui-framework" }

[addresses]
spam = "0x0"
sui = "0x2"
